-- CreateTable
CREATE TABLE "Role" (
    "name" TEXT NOT NULL,
    "permissions" TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Role_pkey" PRIMARY KEY ("name")
);

-- Seed role defaults (idempotent)
INSERT INTO "Role" ("name", "permissions") VALUES
  ('SUPER_ADMIN', '{}'),
  ('ADMIN', '{MANAGE_USERS,MANAGE_EXCHANGE_RATES,MANAGE_RECEIVING_POINTS,MANAGE_LEDGER_ACCOUNTS,GRANT_PERMISSIONS,SYNC_TRANSACTIONS,VIEW_ALL_TRANSACTIONS,VIEW_REPORTS,VIEW_AGENT_REPORTS,VIEW_PAYMENT_REPORTS,VIEW_LEDGER_STATEMENT,EDIT_TRANSACTIONS,DELETE_TRANSACTIONS,CREATE_TRANSACTIONS,CREATE_SENDERS,VIEW_SENDERS,EDIT_SENDERS,CREATE_RECEIVERS,VIEW_RECEIVERS,EDIT_RECEIVERS,VIEW_RECONCILIATIONS,APPROVE_RECONCILIATION,MANAGE_VAULT_TRANSFERS,MARK_PAID}'),
  ('MANAGER', '{SYNC_TRANSACTIONS,VIEW_ALL_TRANSACTIONS,VIEW_REPORTS,VIEW_AGENT_REPORTS,VIEW_PAYMENT_REPORTS,VIEW_LEDGER_STATEMENT,MANAGE_VAULT_TRANSFERS,APPROVE_RECONCILIATION,VIEW_RECONCILIATIONS,CREATE_TRANSACTIONS,CREATE_SENDERS,VIEW_SENDERS,EDIT_SENDERS,CREATE_RECEIVERS,VIEW_RECEIVERS,EDIT_RECEIVERS,EDIT_TRANSACTIONS,DELETE_TRANSACTIONS,MARK_PAID}'),
  ('TELLER', '{MARK_PAID,MANAGE_TELLER_TILL,CREATE_RECONCILIATION,VIEW_RECONCILIATIONS,VIEW_SENDERS,VIEW_RECEIVERS}'),
  ('SENDING_AGENT', '{CREATE_TRANSACTIONS,CREATE_SENDERS,VIEW_SENDERS,VIEW_RECEIVERS,CREATE_RECEIVERS,VIEW_RECONCILIATIONS}')
ON CONFLICT ("name") DO NOTHING;
